import test from "node:test";
import assert from "node:assert/strict";
import { analyze, exitPrice, indicators, nextTick, PERIOD, plan, type Candle } from "../src/lib/trading/strategy.ts";
import { paperCycle } from "../src/lib/trading/paper.ts";
import type { BotState } from "../src/lib/trading/store.ts";
const candles:Candle[]=Array.from({length:500},(_,i)=>{const close=10000+i*2+Math.sin(i*.7)*18;return {time:i*PERIOD,end:(i+1)*PERIOD-1,open:close-2,high:close+8,low:close-8,close,volume:100};});
function state():BotState{return {mode:"paper",pending:null,enabled:true,generation:"test",nextAt:null,lastAt:null,workflowId:null,error:null,warning:null,lastCandle:0,balance:1000,day:"",dayBalance:1000,losses:0,position:null,signal:null,history:[],trades:[]};}
test("wake-up is aligned to candle close plus five seconds",()=>{assert.equal(nextTick(PERIOD+4999),PERIOD+5000);assert.equal(nextTick(PERIOD+5000),PERIOD*2+5000);});
test("finite indicators with warmup and volume gate",()=>{const rows=indicators(candles);assert.ok(Number.isNaN(rows[198].trend));assert.ok(Number.isFinite(rows[199].trend));assert.ok(Number.isFinite(rows.at(-1)!.adx));assert.equal(analyze(candles.map((c,i)=>({...c,volume:i===499?1:100}))).side,"WAIT");});
test("risk cap and conservative stop/target collision",()=>{const p=plan(candles,"LONG",1000)!;assert.ok(p);assert.ok(p.quantity*Math.abs(p.entry-p.stop)<=5);assert.ok(p.quantity*p.entry<=1000);assert.equal(exitPrice({...p,opened:0},{...candles[0],open:p.entry,high:p.target+1,low:p.stop-1}),p.stop);assert.equal(exitPrice({...p,opened:0},{...candles[0],open:p.stop-10,low:p.stop-12,high:p.entry}),p.stop-10);});
test("same candle replay preserves accounting and cannot re-enter",()=>{const s=state(),now=500*PERIOD+5000;paperCycle(s,candles,candles.at(-1)!.close,now);const before=JSON.stringify({...s,lastAt:null,nextAt:null});paperCycle(s,candles,candles.at(-1)!.close,now+10000);assert.equal(JSON.stringify({...s,lastAt:null,nextAt:null}),before);});
test("recover missed exits once, charge both fills, no immediate reentry",()=>{const s=state(),c=candles.at(-1)!;s.lastCandle=candles.at(-2)!.time;s.position={side:"LONG",entry:c.close,stop:c.low+1,target:c.high+100,quantity:1,opened:c.time};s.trades=[{id:1,side:"LONG",status:"OPEN",entryTime:new Date(c.time).toISOString(),exitTime:null,entry:c.close,exit:null,pnl:null,result:null}];paperCycle(s,candles,c.close,c.end+5001);assert.equal(s.position,null);assert.equal(s.trades.length,1);assert.equal(s.trades[0].status,"CLOSED");assert.ok(s.balance<1000);const balance=s.balance;paperCycle(s,candles,c.close,c.end+10000);assert.equal(s.balance,balance);});
test("late wake-up never enters a stale candle",()=>{const s=state();paperCycle(s,candles,candles.at(-1)!.close,500*PERIOD+180000);assert.equal(s.position,null);assert.ok(s.signal!.reasons.includes("지연된 신호의 신규 진입 생략"));});
