"use client";
import { useEffect, useState } from "react";
import type { ExchangeView } from "@/lib/trading/exchange-view";
type Settings={environment:"testnet"|"mainnet";leverage:number;sizing:"auto"|"fixed";margin:number};
const money=(n:number|null)=>n==null?"—":n.toLocaleString("ko-KR",{maximumFractionDigits:5});
const orderLabel=(t:string)=>({STOP_MARKET:"손절 시장가",STOP:"손절",TAKE_PROFIT_MARKET:"익절 시장가",TAKE_PROFIT:"익절",LIMIT:"지정가",TRAILING_STOP_MARKET:"추적 손절"}[t]||t);
function PriceLines({position,orders}:{position:ExchangeView["positions"][number];orders:ExchangeView["orders"]}){
  const points=[{name:"진입",price:position.entry},{name:"마크",price:position.mark},...orders.filter(o=>o.symbol===position.symbol&&o.side===(position.side==="LONG"?"SELL":"BUY")&&(o.positionSide==="BOTH"||o.positionSide===position.side)&&o.trigger&&o.trigger>0).map(o=>({name:orderLabel(o.type),price:o.trigger}))].filter(p=>p.price!=null&&p.price>0);
  if(!points.length)return null;
  const low=Math.min(...points.map(p=>p.price!)),high=Math.max(...points.map(p=>p.price!)),range=high-low||high*.01;
  return <div style={{marginTop:16}} aria-label={`${position.symbol} 진입·마크·손절·익절 가격`}><svg viewBox={`0 0 720 ${points.length*34+12}`} role="img" aria-label="포지션 가격선">{points.map((p,i)=>{const x=190+(p.price!-low)/range*350;return <g key={i}><text x="0" y={i*34+24} fontSize="12" fill="#55706a">{p.name} {money(p.price)}</text><line x1="185" x2="705" y1={i*34+20} y2={i*34+20} stroke="#e0e9e4"/><circle cx={x} cy={i*34+20} r="5" fill={p.name.includes("손절")?"#bb594f":p.name.includes("익절")?"#278466":"#738590"}/></g>;})}</svg></div>;
}
export default function TradingPanel({environment,exchange,error}:{environment:Settings["environment"];exchange:ExchangeView|null;error:string|null}){
  const [settings,setSettings]=useState<Settings|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;setSettings(null);setMessage("");fetch(`/api/settings?environment=${environment}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setSettings(d.settings);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[environment]);
  const view=exchange?.environment===environment?exchange:null;
  return <>
    <section className="card" style={{marginBottom:24}}><h2>자동매매 진입 설정 · {environment==="testnet"?"Demo":"실계정"}</h2><p>BTCUSDT 신규 진입에 적용합니다. 저장해도 기존 포지션의 배수와 손절·익절 주문은 바뀌지 않습니다.</p>{settings&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><div className="position-values"><span><label htmlFor="trade-leverage">배수 (1~125배)</label><input id="trade-leverage" type="number" min="1" max="125" step="1" required value={settings.leverage} onChange={e=>setSettings({...settings,leverage:Number(e.target.value)})}/></span><span><label htmlFor="trade-sizing">진입금액 방식</label><select id="trade-sizing" value={settings.sizing} onChange={e=>setSettings({...settings,sizing:e.target.value as Settings["sizing"]})}><option value="auto">자동 위험 한도</option><option value="fixed">직접 지정</option></select></span><span><label htmlFor="trade-margin">진입 증거금 (USDT)</label><input id="trade-margin" type="number" min="1" max="1000000" step="0.01" required disabled={settings.sizing!=="fixed"} value={settings.margin} onChange={e=>setSettings({...settings,margin:Number(e.target.value)})}/></span></div><p>{settings.sizing==="fixed"?`예상 포지션 금액 ${money(settings.margin*settings.leverage)} USDT = 증거금 × 배수. 수량 단위와 체결 가격에 따라 달라집니다.`:"손절 거리와 잔고에 따라 수량을 자동 계산합니다."} 거래소가 허용하지 않는 배수·최소 주문 금액이나 잔고 부족 시 진입이 제한됩니다.</p><button className="primary" style={{maxWidth:240}} disabled={busy}>{busy?"저장 중…":"진입 설정 저장"}</button></form>}{message&&<p role="status">{message}</p>}</section>
    <section className="card" style={{marginBottom:24}}><div className="card-heading"><div><h2>거래소 현재 포지션</h2><p>선택한 계정 전체 심볼 · 15초마다 조회 · 봇 외부 포지션도 표시</p></div><span className="subtle-tag">{view?.positions.length??"—"}건</span></div>{error?<p className="error">{error}</p>:!view?<p>저장된 API 키와 조회 연결을 확인하세요.</p>:!view.positions.length?<p>거래소에 보유 중인 포지션이 없습니다.</p>:view.positions.map((p,i)=><div key={`${p.symbol}-${p.side}-${i}`} style={{borderTop:"1px solid #e0e9e4",paddingTop:16}}><h3>{p.symbol} · {p.side==="LONG"?"매수 롱":"매도 숏"}</h3><div className="position-values"><span>수량<strong>{money(p.quantity)}</strong></span><span>진입가<strong>{money(p.entry)}</strong></span><span>마크 가격<strong>{money(p.mark)}</strong></span><span>청산가<strong>{p.liquidation&&p.liquidation>0?money(p.liquidation):"—"}</strong></span><span>미실현 손익<strong>{money(p.pnl)} USDT</strong></span></div><PriceLines position={p} orders={view.orders}/></div>)}{view&&<p>조회 {new Date(view.queriedAt).toLocaleTimeString("ko-KR",{timeZone:"Asia/Seoul"})}</p>}</section>
    <section className="card" style={{marginBottom:24}}><div className="card-heading"><div><h2>오픈오더 · 손절·익절</h2><p>일반 미체결 주문과 조건부 주문 · 거래소 조회 전용</p></div><span className="subtle-tag">{view?.orders.length??"—"}건</span></div>{error?<p className="error">{error}</p>:view?<div className="table-scroll"><table><thead><tr><th>심볼</th><th>주문 유형</th><th>매매 방향</th><th>주문 가격</th><th>발동 가격</th><th>수량</th><th>발동 기준</th><th>상태</th></tr></thead><tbody>{view.orders.length?view.orders.map(o=><tr key={o.id}><td>{o.symbol}</td><td>{orderLabel(o.type)}</td><td>{o.side==="BUY"?"매수":"매도"}</td><td>{o.price&&o.price>0?money(o.price):"시장가"}</td><td>{o.trigger&&o.trigger>0?money(o.trigger):"—"}</td><td>{o.closePosition?"전체 포지션 청산":money(o.quantity)}</td><td>{o.workingType==="MARK_PRICE"?"마크 가격":"거래 가격"}</td><td>{o.status}</td></tr>):<tr><td colSpan={8}>거래소에 미체결·조건부 주문이 없습니다.</td></tr>}</tbody></table></div>:<p>저장된 API 키와 조회 연결을 확인하세요.</p>}</section>
  </>;
}

